// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class ZSurvival
{
        public const string achievement_wave_11 = "CgkI243Yh90ZEAIQBA"; // <GPGSID>
        public const string achievement_wave_13 = "CgkI243Yh90ZEAIQBQ"; // <GPGSID>
        public const string achievement_wave_15 = "CgkI243Yh90ZEAIQBg"; // <GPGSID>
        public const string achievement_wave_19 = "CgkI243Yh90ZEAIQCA"; // <GPGSID>
        public const string achievement_wave_17 = "CgkI243Yh90ZEAIQBw"; // <GPGSID>
        public const string achievement_wave_5 = "CgkI243Yh90ZEAIQAQ"; // <GPGSID>
        public const string achievement_wave_7 = "CgkI243Yh90ZEAIQAg"; // <GPGSID>
        public const string achievement_wave_9 = "CgkI243Yh90ZEAIQAw"; // <GPGSID>
        public const string leaderboard_ranking = "CgkI243Yh90ZEAIQDA"; // <GPGSID>
        public const string achievement_wave_21 = "CgkI243Yh90ZEAIQCQ"; // <GPGSID>
        public const string achievement_wave_3 = "CgkI243Yh90ZEAIQAA"; // <GPGSID>

}

